name: learnobot
description: An AI-based agent for mediating instructions for struggling students

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  flutter_rating_bar: ^4.0.1
  
  # For functionality 
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  http: ^0.13.6
  camera: ^0.10.5
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  image_picker: ^0.8.7+5
  intl: 0.19.0
  
  # Firebase (or can be replaced with your preferred backend)
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    
  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Regular.ttf
        - asset: assets/fonts/Heebo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Heebo-Bold.ttf
          weight: 700